messages:
  no permission: "&c&l(!) You don't have permission!"
  not dupable: "&c&l(!) Not Dupable."
  
settings:
  stack size: 64
  allow duping rarity books: true
  allow duping enchant books: true
  
blacklist:
  - "RAGE" # Prevents duping the rage enchant book
  - "ELITE" # Prevents duping the (unopened) elite enchantment book